### ISSUE TITLE
Progress Tracking

### ISSUE THREAD

**Issue by DavidLuptak** [MartinStyk/quotes-recommender#1]
This is a checklist what to do and what is already done (checkbox buttons are clickable).

Data:
* [x] retrieve data (quote, author, categories)

Ruby on Rails application:
* [x] base application
* [x] import data (CSV -> DB)
* [x] OAuth authentication
* [x] user roles (user, admin)
* [x] quote ratings
* [x] strategy for user
* [x] <del> do tests</del> 
* [x] ...
* [x] deploy the app (OpenShift / Heroku)

Recommendations:
* [x] <del> how to measure time spent on the website?</del> 
* [x] <del>  generate random ratings for quotes</del> 
* [x] implement recommendations

**Comment by DavidLuptak** [comment]
The project is done.
